// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProLibrary.Models;

#nullable disable

namespace ProLibrary.Migrations
{
    [DbContext(typeof(PROContext))]
    [Migration("20231102145841_AddAuthTMIUserTable")]
    partial class AddAuthTMIUserTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProLibrary.Models.DcMetadata", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("ITEM_ID");

                    b.Property<string>("Host")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("HOST");

                    b.Property<string>("ItemComment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("ITEM_COMMENT");

                    b.Property<string>("ItemContainer")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ITEM_CONTAINER");

                    b.Property<string>("ItemName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ITEM_NAME");

                    b.Property<string>("ItemSource")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ITEM_SOURCE");

                    b.Property<string>("ItemType")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ITEM_TYPE");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("LAST_MODIFIED_AT");

                    b.Property<double?>("MaxVal")
                        .HasColumnType("float")
                        .HasColumnName("MAX_VAL");

                    b.Property<double?>("MinVal")
                        .HasColumnType("float")
                        .HasColumnName("MIN_VAL");

                    b.Property<string>("Orientation")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ORIENTATION");

                    b.Property<double?>("Scaling")
                        .HasColumnType("float")
                        .HasColumnName("SCALING");

                    b.Property<string>("Sensor")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("SENSOR");

                    b.Property<string>("Unit")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("UNIT");

                    b.Property<double?>("UpdateCycle")
                        .HasColumnType("float")
                        .HasColumnName("UPDATE_CYCLE");

                    b.HasKey("ItemId")
                        .HasName("DC_METADATA_PK");

                    b.ToTable("DC_METADATA", "PRO");
                });

            modelBuilder.Entity("ProLibrary.Models.TmiUser", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("USERNAME");

                    b.Property<string>("FirstName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<string>("LandingPage")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("LANDING_PAGE");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("LAST_MODIFIED_AT");

                    b.Property<string>("LastName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("LAST_NAME");

                    b.Property<byte[]>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("varbinary(512)")
                        .HasColumnName("PASSWORD_HASH");

                    b.Property<byte[]>("PasswordSalt")
                        .HasMaxLength(512)
                        .HasColumnType("varbinary(512)")
                        .HasColumnName("PASSWORD_SALT");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("ROLE_NAME");

                    b.HasKey("Username")
                        .HasName("TMI_USER_PK");

                    b.ToTable("TMI_USER", "PRO");
                });
#pragma warning restore 612, 618
        }
    }
}
